### ISSUE TITLE
soundfile format

### ISSUE THREAD

**Issue by derrgis** [sleemanj/JQ6500_Serial#17]
Hello,
Sorry if this is not the right place to relate.
I get something good uploading one single 10sec. mp3 soundfile with a 45-85Kbps compression.
However, if I upload more than one file the sound is saturated for each.
This is not a power issue.
What file encoding do someone uses ?
Is there something special to know with file upload.

**Comment by sleemanj** [comment]
MP3 Format
The devices can play most Stereo MP3 files.   

I found that a “Joint-stereo” file did not appear to work, but simply re-encoding to an ordinary stereo file was fine – I use the LAME Audio Encoder to re-encode it, “lame -m s inFile.mp3 outFile.mp3”, see below for other tips about re-encoding files.

The following sampling rates are supported:  8 / 11.025 / 12 / 16 / 22.05 / 24/32 / 44.1 / 48 kHz

SD Card Files
The 28P can support (supposedly, not tested) up to 32g Micro SD Card (aka TransFlash / TF), files can be split into up to 100 folders, with 1000 files. 

Any old file names work fine.

It’s unclear which files the 5 “hotkeys” correspond to but I suspect it is the first 5 files in the FAT table (Google for a FAT sorter utility suitable for your operating system), although there is a mention in the datasheet of naming folders 00 .. 99 and the files within the folders 001.mp3 .. 999.mp3 so that may have something to do with it (or might just be convenient to name them like that and use a FAT sorter). 

Tips for Re-encoding files
For the 16P particularly due to the limited space in the on board flash, you may wish (need) to re-encode your MP3 files to shrink them, using a lower bitrate.  The utility program “lame” can do this on the command line easily for Linux and Mac (obviously once you install it) the phone preset reduces the files to 16kHz and 16kbps which can reduce files significantly (with commensurate loss of quality).

$ lame --preset phone inputFile.mp3 outputFile.mp3
Or to really get it down, add -B 8 --resample 8 to the command in order to bring it down to 8kHz and 8kbps.

On Windows, try winLAME

For the 28P if you are using an SD Card, you might as well stick with higher quality and get a bigger SD Card :-)

**Comment by thijstriemstra** [comment]
> The 28P can support (supposedly, not tested) up to 32g Micro SD Card (aka TransFlash / TF), 

I just tested with a 32GB FAT formatted SD-card, and it's not playing any of the files. I tried 16GB before and that worked fine. I'll more closely examine the differences between the 2 sd-cards.

**Update**:

| Brand | Size | Filesystem | Working |
| --- | --- | --- | --- |
| Transcend Class 10 | 32 GB | `W95 FAT32 (LBA)` | no |
| Sandisk UltraClass 10 | 16 GB | `W95 FAT32 (LBA)` | yes |

**Update 2**:

It seems to work afterall when I copy the same contents and directory structure. Odd, I didn't know there was a requirement for a certain directory structure. Anyway, this structure works:

```console
/media/thijs/3637-3731/:
total 128
drwxr-xr-x 2 thijs thijs 32768 jul  2 18:31 01
drwxr-xr-x 2 thijs thijs 32768 jul  1 18:49 02
drwxr-xr-x 2 thijs thijs 32768 jul  1 18:50 03
drwxr-xr-x 2 thijs thijs 32768 jul  1 18:51 04

/media/thijs/3637-3731/01:
total 34272
-rw-r--r-- 1 thijs thijs 7125913 jun 23 22:52 '001 The Lord Of The Rings (Howard Shore) - Concerning Hobbits.mp3'
-rw-r--r-- 1 thijs thijs 9524999 jun 23 22:56 '002 The Lord Of The Rings (Howard Shore) - The Prophecy.mp3'
-rw-r--r-- 1 thijs thijs 8643105 jun 23 22:51 '003 The Lord Of The Rings (Howard Shore) - The Shadow of the Past.mp3'
-rw-r--r-- 1 thijs thijs 9750696 jun 23 22:56 '004 The Lord Of The Rings (Howard Shore) - The Treason of Isengard.mp3'

/media/thijs/3637-3731/02:
total 25760
-rw-r--r-- 1 thijs thijs 9436558 jun 23 22:56 '005 The Lord Of The Rings (Howard Shore) - Foundations of Stone.mp3'
-rw-r--r-- 1 thijs thijs 6914175 jun 23 22:56 '006 The Lord Of The Rings (Howard Shore) - The Taming of Smeagol.mp3'
-rw-r--r-- 1 thijs thijs 9979905 jun 23 22:56 '007 The Lord Of The Rings (Howard Shore) - The Riders of Rohan.mp3'

/media/thijs/3637-3731/03:
total 34752
-rw-r--r-- 1 thijs thijs  5309475 jun 16 19:59 '008. John Williams - Prologue.mp3'
-rw-r--r-- 1 thijs thijs 12847397 jun 16 19:58 "009. John Williams - Harry's Wondrous World.mp3"
-rw-r--r-- 1 thijs thijs 10620726 jun 16 20:05 '010. John Williams - The Arrival Of Baby Harry.mp3'
-rw-r--r-- 1 thijs thijs  6701352 jun 16 18:51 '011. John Williams - The Norwegian Ridgeback - A Change Of Season.mp3'

/media/thijs/3637-3731/04:
total 25792
-rw-r--r-- 1 thijs thijs 10555175 jun 23 22:41 '012. Ahch-To Island.mp3'
-rw-r--r-- 1 thijs thijs  7231260 jun 23 22:42 '013. The Cave.mp3'
-rw-r--r-- 1 thijs thijs  8554294 jun 23 22:42 '014. The Sacred Jedi Texts.mp3'
```
