### ISSUE TITLE
move to HW serial

### ISSUE THREAD

**Issue by pipersw** [sleemanj/JQ6500_Serial#2]
I use Timer1 interrupt in my software, and there is a conflict with SoftwareSerial.h because it use interrupt too.

Could you add the choice of use hardware serial ?
Where is the JQ6500 datasheet ?
thx

**Comment by sleemanj** [comment]
Datasheet: http://www.jq0755.com/Uploads/2014619180144105.pdf

For move to HardwareSerial, you can probably just change SoftwareSerial to HardwareSerial in JQ6500_Serial.h and change the constructor also on
https://github.com/sleemanj/JQ6500_Serial/blob/master/JQ6500_Serial.h#L112
to be appropriate for hardware serial (specify baud instead of tx/rx etc).

`

**Comment by thijstriemstra** [comment]
See #32
